// Generated by https://quicktype.io

namespace SSResurrezioneBR.Models.Options
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class CoroPolifonicoMaterMisericordieOptions
    {
        public long PerPage { get; set; }
        public CoroPolifonicoMaterMisericordieOrderOptions Order { get; set; }
    }

    public partial class CoroPolifonicoMaterMisericordieOrderOptions
    {
        public string By { get; set; }
        public bool Ascending { get; set; }
        public string[] Allow { get; set; }
    }
}