// Generated by https://quicktype.io

namespace SSResurrezioneBR.Models.Options
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class SSResurrezioneOptions
    {
        public long PerPage { get; set; }
        public SSResurrezioneOrderOptions Order { get; set; }
    }

    public partial class SSResurrezioneOrderOptions
    {
        public bool Ascending { get; set; }
        public string[] Allow { get; set; }
    }
}